# Generated by Django 2.2.2 on 2019-08-06 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proprietaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('prenom', models.CharField(max_length=50)),
                ('sexe', models.CharField(max_length=1)),
                ('telephone', models.CharField(max_length=20)),
                ('adresse', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=25)),
                ('fonction', models.CharField(max_length=25)),
                ('num_pieceid', models.CharField(max_length=15)),
            ],
        ),
    ]
