# Generated by Django 2.2.4 on 2019-08-07 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lands', '0004_auto_20190807_1006'),
    ]

    operations = [
        migrations.CreateModel(
            name='Typeparcelle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libTypeParcelle', models.CharField(max_length=30)),
            ],
        ),
    ]
