# Generated by Django 2.2.4 on 2019-08-19 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lands', '0005_typeparcelle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parcelle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
