# Generated by Django 2.2.4 on 2019-09-02 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
        ('lands', '0006_parcelle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fichier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.CharField(max_length=254)),
            ],
        ),
        migrations.AddField(
            model_name='parcelle',
            name='dide',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parcelle',
            name='nomGeometre',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parcelle',
            name='numApprobation',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parcelle',
            name='numIdFiscal',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parcelle',
            name='numLot',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parcelle',
            name='numTitreFoncier',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parcelle',
            name='quartier',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='location.Quartier'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parcelle',
            name='typeParcelle',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='lands.Typeparcelle'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='HistoriqueProprio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parcelle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lands.Parcelle')),
                ('proprietaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lands.Proprietaire')),
                ('typeSuccession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lands.Typesuccession')),
            ],
        ),
    ]
