# Generated by Django 2.2.4 on 2019-09-05 18:58

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lands', '0007_auto_20190902_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcelle',
            name='coordonee',
            field=django.contrib.gis.db.models.fields.PolygonField(default=None, srid=4326),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parcelle',
            name='surface',
            field=models.FloatField(default=None),
            preserve_default=False,
        ),
    ]
