# Generated by Django 2.2.4 on 2019-09-06 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lands', '0008_auto_20190905_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcelle',
            name='surface',
            field=models.FloatField(null=True),
        ),
    ]
