# Generated by Django 2.2.4 on 2019-09-11 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lands', '0010_auto_20190906_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proprietaire',
            name='telephone',
            field=models.CharField(max_length=30),
        ),
    ]
