# Generated by Django 2.2.4 on 2019-09-13 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lands', '0011_auto_20190911_2055'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichier',
            name='parcelle',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='lands.Parcelle'),
            preserve_default=False,
        ),
    ]
