# Generated by Django 2.2.4 on 2019-09-14 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lands', '0012_fichier_parcelle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichier',
            name='file',
            field=models.FileField(upload_to=''),
        ),
    ]
