# Generated by Django 2.2.4 on 2019-09-14 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lands', '0014_auto_20190914_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichier',
            name='file',
            field=models.CharField(max_length=255),
        ),
    ]
