# Generated by Django 2.2.2 on 2019-08-05 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Canton',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libCanton', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libRegion', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Village',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libVillage', models.CharField(max_length=30)),
                ('canton', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.Canton')),
            ],
        ),
        migrations.CreateModel(
            name='Quartier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libQuartier', models.CharField(max_length=30)),
                ('village', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.Village')),
            ],
        ),
        migrations.CreateModel(
            name='Prefecture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liPrefecture', models.CharField(max_length=30)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.Region')),
            ],
        ),
        migrations.CreateModel(
            name='Commune',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libCommune', models.CharField(max_length=30)),
                ('prefecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.Prefecture')),
            ],
        ),
        migrations.AddField(
            model_name='canton',
            name='commune',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.Commune'),
        ),
    ]
